#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 26 16:53:56 CET 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim test_tb_behav -key {Behavioral:sim_1:Functional:test_tb} -tclbatch test_tb.tcl -view /home/sebin/Documents/CSA/lowrisc_ibex_top_artya7_0.1/synth-vivado/test_tb_behav.wcfg -log simulate.log"
xsim test_tb_behav -key {Behavioral:sim_1:Functional:test_tb} -tclbatch test_tb.tcl -view /home/sebin/Documents/CSA/lowrisc_ibex_top_artya7_0.1/synth-vivado/test_tb_behav.wcfg -log simulate.log

