fusesoc-deps := \
  /home/sebin/Documents/CSA/ibex/examples/fpga/artya7/top_artya7.core \
  /home/sebin/Documents/CSA/ibex/examples/fpga/artya7/rtl/top_artya7.sv \
  /home/sebin/Documents/CSA/ibex/examples/fpga/artya7/data/pins_artya7.xdc \
  /home/sebin/Documents/CSA/ibex/shared/fpga_xilinx.core \
  /home/sebin/Documents/CSA/ibex/shared/rtl/fpga/xilinx/clkgen_xil7series.sv \
  /home/sebin/Documents/CSA/ibex/shared/rtl/ram_1p.sv \
  /home/sebin/Documents/CSA/ibex/ibex_core.core \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_alu.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_branch_predict.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_compressed_decoder.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_controller.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_cs_registers.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_csr.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_counter.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_decoder.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_ex_block.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_fetch_fifo.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_id_stage.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_if_stage.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_load_store_unit.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_multdiv_fast.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_multdiv_slow.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_prefetch_buffer.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_pmp.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_wb_stage.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_dummy_instr.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_register_file_ff.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_register_file_fpga.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_register_file_latch.sv \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_core.sv \
  /home/sebin/Documents/CSA/ibex/check_tool_requirements.core \
  /home/sebin/Documents/CSA/ibex/util/check_tool_requirements.py \
  /home/sebin/Documents/CSA/ibex/tool_requirements.py \
  /home/sebin/Documents/CSA/ibex/ibex_icache.core \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_icache.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/prim_ram_1p.core \
  /home/sebin/Documents/CSA/ibex/build/lowrisc_ibex_top_artya7_0.1/synth-vivado/generated/lowrisc_prim_ram_1p-impl_0/prim_ram_1p.core \
  /home/sebin/Documents/CSA/ibex/build/lowrisc_ibex_top_artya7_0.1/synth-vivado/generated/lowrisc_prim_ram_1p-impl_0/prim_ram_1p.sv \
  /home/sebin/Documents/CSA/ibex/dv/uvm/icache/dv/prim_badbit/prim_badbit_ram_1p.core \
  /home/sebin/Documents/CSA/ibex/dv/uvm/icache/dv/prim_badbit/prim_badbit_ram_1p.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim_generic/prim_generic_ram_1p.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim_generic/rtl/prim_generic_ram_1p.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/prim_util_memload.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_util_memload.svh \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/primgen.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/prim_pkg.core \
  /home/sebin/Documents/CSA/ibex/build/lowrisc_ibex_top_artya7_0.1/synth-vivado/generated/lowrisc_prim_prim_pkg-impl_0.1/prim_pkg.core \
  /home/sebin/Documents/CSA/ibex/build/lowrisc_ibex_top_artya7_0.1/synth-vivado/generated/lowrisc_prim_prim_pkg-impl_0.1/prim_pkg.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/prim_secded.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_secded_28_22_dec.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_secded_28_22_enc.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_secded_39_32_dec.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_secded_39_32_enc.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_secded_72_64_dec.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_secded_72_64_enc.sv \
  /home/sebin/Documents/CSA/ibex/ibex_pkg.core \
  /home/sebin/Documents/CSA/ibex/rtl/ibex_pkg.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/prim_lfsr.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_lfsr.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/prim_clock_gating.core \
  /home/sebin/Documents/CSA/ibex/build/lowrisc_ibex_top_artya7_0.1/synth-vivado/generated/lowrisc_prim_clock_gating-impl_0/prim_clock_gating.core \
  /home/sebin/Documents/CSA/ibex/build/lowrisc_ibex_top_artya7_0.1/synth-vivado/generated/lowrisc_prim_clock_gating-impl_0/prim_clock_gating.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim_xilinx/prim_xilinx_clock_gating.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim_xilinx/rtl/prim_xilinx_clock_gating.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim_generic/prim_generic_clock_gating.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim_generic/rtl/prim_generic_clock_gating.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/prim_assert.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_assert.sv \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_assert_dummy_macros.svh \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_assert_yosys_macros.svh \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/rtl/prim_assert_standard_macros.svh \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/primgen.core \
  /home/sebin/Documents/CSA/ibex/vendor/lowrisc_ip/prim/util/primgen.py
